### ISSUE TITLE
invalid crypted content checksum

### ISSUE THREAD

**Issue by cbbravo** [bvanheu/stratasys#47]
I have the following xxd outputs:

> xxd -p id_2017-04-28_original
> 238785410100001a

> xxd -p eeprom_2017-04-28_original
> 1d3bcdd6826485d60a8fe69566fe8ad8bb8e1bf2ed123289d97286516ed3
> 80f68165e6a73b1a6b0c52e57fe23e2c218252e57fe23e2c21829afe53d4
> 2da8af43ac7600000000a64d55aa551b06465dbefeb300000000000040b5
> 6c000a68cfd37ffe84220120a0bf5354524154415379530b821c867b5fa5
> c2282a916d2cc7b7194e67ccc250fc797feec88b05f4fe13f844b5a5c1f0
> 0d259f9a36f57131f6ae0666c53bf4a4cff6a3f29691706d9624c2b4454f
> 6e6b9a7f1d88fad6671294c7b08169100db556cb9633d99792346b3fa1d7
> 695193cf3d78d8a0373003eabecce46338063f09a011a90e990640ff23a6
> f6c924263f478dc69dbcaa11fedad25996f5cfe130e4a08253bdaabeabbd
> aa8ea5b98a4b0e29f4edb81f1df7dcdf4ca395d01a3eb35e201b2284c56a
> 7f3a3312613b220b2ef06cce7b8657f2099518bb89cb4d3219dd07bbef87
> 5ded830dfd2fddc6aee011eb9c2092a8b7bdeb2696b61cb4122da4b15753
> 0fc25d2b005bbd425da5b126dc6e4c8bd6208941bedb44f5bca20aee1e9d
> e8bde3e1f45e8c23b660f41a9eec3b789a1042e83d73039c65e124fba755
> f890277e380eed00649ffbed1d843d8cbb943858a40f260fc97c35b772ca
> 9d5ffc5c377a0ffd4fcfe12b07358ab01b5ad93e3df40f1a2f2224f59fd9
> 5f8f5cb959556ef2038f3e4baeebea1049f1def04a6edce223ce17957e6d

Running the script hits me with
> ./stratasys-cli.py eeprom -t prodigy -e 1a00000141858723 -i eeprom_2017-04-28_original
> Traceback (most recent call last):
>   File "./stratasys-cli.py", line 252, in <module>
>     app.run()
>   File "./stratasys-cli.py", line 27, in run
>     args.func(args)
>   File "./stratasys-cli.py", line 101, in command_eeprom
>     self._eeprom_info(args)
>   File "./stratasys-cli.py", line 211, in _eeprom_info
>     cartridge = m.decode(machine_number, args.eeprom_uid, cartridge_crypted)
>   File "/home/pi/ds2433/stratasys-master/stratasys/manager.py", line 52, in decode
>     cartridge_packed = self.decrypt(machine_number, eeprom_uid, cartridge_crypted)
>   File "/home/pi/ds2433/stratasys-master/stratasys/manager.py", line 197, in decrypt
>     raise Exception("invalid crypted content checksum")
> Exception: invalid crypted content checksum

Want to "re-wire" the 7 meters of filament left in that cartridge.
Running python 2.7.9

So what am I doing wrong here?

**Comment by cbbravo** [comment]
Never mind. The transmission is full of errors. Every time I copy that file from the DS2433 I get a different result. Will try to fix those wires first.
